[context.production.environment]
  ROOT_NOTION_PAGE_ID = "add5e59f30464b439b107db96b53507c"
  NEXT_PUBLIC_SITE_CONFIG = "{\"rootNotionPageId\":\"add5e59f30464b439b107db96b53507c\"}"
  NEXT_ENABLE_ANALYTICS = true

[context.staging.environment]
  ROOT_NOTION_PAGE_ID = "27530080e7ce4d2e8f550cd25b66eb29"
  NEXT_PUBLIC_SITE_CONFIG = "{\"rootNotionPageId\":\"27530080e7ce4d2e8f550cd25b66eb29\"}"
